interface _Writable
  def open: (String path, String mode) -> untyped
end

class Report
  def initialize: (String filepath, **untyped story_config) -> void

  def write_csv: (_Writable path) -> untyped

  def sprint_issues: () -> Array[Hash[Symbol, (String|bool)?]]

  private

  attr_reader filepath: untyped

  attr_reader story_config: untyped

  def contents: () -> untyped
end
